openapi: 3.0.0
info:
  description: "API quản lý sản phẩm cho phép lấy thông tin sản phẩm, lấy sản phẩ\
    m theo ID, thêm sản phẩm mới, cập nhật và xóa sản phẩm."
  title: Product API
  version: 1.0.0
servers:
- url: /
tags:
- description: Các thao tác quản lý sản phẩm
  name: Products
paths:
  /products:
    get:
      operationId: get_all_products
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
                type: array
          description: Lấy danh sách thành công
      summary: Lấy tất cả sản phẩm
      tags:
      - Products
      x-openapi-router-controller: openapi_server.controllers.products_controller
    post:
      operationId: create_product
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "201":
          description: Đã tạo sản phẩm
      summary: Tạo sản phẩm mới
      tags:
      - Products
      x-openapi-router-controller: openapi_server.controllers.products_controller
  /products/{id}:
    delete:
      operationId: delete_product
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Đã xóa thành công
        "404":
          description: Không tìm thấy sản phẩm
      summary: Xóa sản phẩm
      tags:
      - Products
      x-openapi-router-controller: openapi_server.controllers.products_controller
    get:
      operationId: get_product_by_id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Lấy sản phẩm thành công
        "404":
          description: Không tìm thấy sản phẩm
      summary: Lấy sản phẩm theo ID
      tags:
      - Products
      x-openapi-router-controller: openapi_server.controllers.products_controller
    put:
      operationId: update_product
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "200":
          description: Đã cập nhật thành công
        "404":
          description: Không tìm thấy sản phẩm
      summary: Cập nhật sản phẩm
      tags:
      - Products
      x-openapi-router-controller: openapi_server.controllers.products_controller
components:
  schemas:
    Product:
      example:
        price: 15000000
        name: Laptop Acer Aspire Lite 15
        description: Laptop văn phòng
        id: id
        stock: 50
      properties:
        id:
          readOnly: true
          title: id
          type: string
        name:
          example: Laptop Acer Aspire Lite 15
          title: name
          type: string
        price:
          example: 15000000
          title: price
          type: number
        description:
          example: Laptop văn phòng
          title: description
          type: string
        stock:
          example: 50
          title: stock
          type: integer
      title: Product
      type: object
