from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None, status=None):  # noqa: E501
        """BookInput - a model defined in OpenAPI

        :param title: The title of this BookInput.  # noqa: E501
        :type title: str
        :param author: The author of this BookInput.  # noqa: E501
        :type author: str
        :param status: The status of this BookInput.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'title': str,
            'author': str,
            'status': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'status': 'status'
        }

        self._title = title
        self._author = author
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'BookInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookInput of this BookInput.  # noqa: E501
        :rtype: BookInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookInput.


        :return: The title of this BookInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookInput.


        :param title: The title of this BookInput.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookInput.


        :return: The author of this BookInput.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookInput.


        :param author: The author of this BookInput.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def status(self) -> str:
        """Gets the status of this BookInput.


        :return: The status of this BookInput.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this BookInput.


        :param status: The status of this BookInput.
        :type status: str
        """
        allowed_values = ["available", "borrowed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
