from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ThMSChMI400Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, message=None, errors=None):  # noqa: E501
        """ThMSChMI400Response - a model defined in OpenAPI

        :param success: The success of this ThMSChMI400Response.  # noqa: E501
        :type success: bool
        :param message: The message of this ThMSChMI400Response.  # noqa: E501
        :type message: str
        :param errors: The errors of this ThMSChMI400Response.  # noqa: E501
        :type errors: List[object]
        """
        self.openapi_types = {
            'success': bool,
            'message': str,
            'errors': List[object]
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message',
            'errors': 'errors'
        }

        self._success = success
        self._message = message
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'ThMSChMI400Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Th_m_s_ch_m_i_400_response of this ThMSChMI400Response.  # noqa: E501
        :rtype: ThMSChMI400Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this ThMSChMI400Response.


        :return: The success of this ThMSChMI400Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this ThMSChMI400Response.


        :param success: The success of this ThMSChMI400Response.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this ThMSChMI400Response.


        :return: The message of this ThMSChMI400Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ThMSChMI400Response.


        :param message: The message of this ThMSChMI400Response.
        :type message: str
        """

        self._message = message

    @property
    def errors(self) -> List[object]:
        """Gets the errors of this ThMSChMI400Response.


        :return: The errors of this ThMSChMI400Response.
        :rtype: List[object]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[object]):
        """Sets the errors of this ThMSChMI400Response.


        :param errors: The errors of this ThMSChMI400Response.
        :type errors: List[object]
        """

        self._errors = errors
