from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class XASChTheoID204Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, message=None):  # noqa: E501
        """XASChTheoID204Response - a model defined in OpenAPI

        :param success: The success of this XASChTheoID204Response.  # noqa: E501
        :type success: bool
        :param message: The message of this XASChTheoID204Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'success': bool,
            'message': str
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message'
        }

        self._success = success
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'XASChTheoID204Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The X_a_s_ch_theo_ID_204_response of this XASChTheoID204Response.  # noqa: E501
        :rtype: XASChTheoID204Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this XASChTheoID204Response.


        :return: The success of this XASChTheoID204Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this XASChTheoID204Response.


        :param success: The success of this XASChTheoID204Response.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this XASChTheoID204Response.


        :return: The message of this XASChTheoID204Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this XASChTheoID204Response.


        :param message: The message of this XASChTheoID204Response.
        :type message: str
        """

        self._message = message
