from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DELETEBooksId204Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, message=None):  # noqa: E501
        """DELETEBooksId204Response - a model defined in OpenAPI

        :param success: The success of this DELETEBooksId204Response.  # noqa: E501
        :type success: bool
        :param message: The message of this DELETEBooksId204Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'success': bool,
            'message': str
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message'
        }

        self._success = success
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'DELETEBooksId204Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DELETE_books_id_204_response of this DELETEBooksId204Response.  # noqa: E501
        :rtype: DELETEBooksId204Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this DELETEBooksId204Response.


        :return: The success of this DELETEBooksId204Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this DELETEBooksId204Response.


        :param success: The success of this DELETEBooksId204Response.
        :type success: bool
        """
        if success is None:
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this DELETEBooksId204Response.


        :return: The message of this DELETEBooksId204Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this DELETEBooksId204Response.


        :param message: The message of this DELETEBooksId204Response.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
